version: '3'
services:
  backend:
    image: docker-backend:latest
    platform: linux/x86_64
    ports:
      - 8000:8000
  
  frontend:
    image: docker-frontend:latest
    platform: linux/x86_64
    ports:
      - 3000:3000
